#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Clean up transaction artifacts generated by this repo for a given tx hash
(transactions/<tx>/ + log/tx_* + source exports + decompilation output, etc.).

Usage (from repo root):
  source venv/bin/activate
  python scripts/cleanup.py --tx 0x...

Recommended: preview with dry-run first:
  python scripts/cleanup.py --tx 0x... --dry-run
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path
from typing import Iterable, Optional, Set

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))


def _as_repo_path(repo_root: Path, p: str | Path) -> Path:
    """Convert a relative path to an absolute path under repo_root; absolute paths are returned as-is."""
    pp = Path(p)
    if not pp.is_absolute():
        pp = (repo_root / pp).resolve()
    else:
        pp = pp.resolve()
    return pp


def _is_under(path: Path, root: Path) -> bool:
    try:
        path.resolve().relative_to(root.resolve())
        return True
    except Exception:
        return False


def _safe_remove(path: Path, *, repo_root: Path, dry_run: bool) -> bool:
    """
    Safe delete: only allows deleting paths inside repo_root.
    Returns: whether the item was actually deleted / would be deleted (dry-run counts as True).
    """
    path = path.resolve()
    if not path.exists():
        return False

    if not _is_under(path, repo_root):
        raise RuntimeError(f"Refusing to delete path outside repo: {path}")

    if dry_run:
        print(f"[dry-run] remove: {path}")
        return True

    if path.is_dir():
        shutil.rmtree(path)
    else:
        path.unlink()
    print(f"removed: {path}")
    return True


def _iter_contract_files(log_dir: Path, tx_short: str) -> Iterable[Path]:
    yield from sorted(log_dir.glob(f"tx_contracts_{tx_short}_*.json"))


def _extract_paths_from_contracts_file(
    contracts_file: Path,
    *,
    repo_root: Path,
) -> tuple[Set[Path], Set[Path], Set[Path]]:
    """
    Returns three sets of paths:
    - files: files to delete
    - dirs: directories to delete
    - output_local_candidates: Heimdall artifacts under output/local (inferred by address)
    """
    files: Set[Path] = set()
    dirs: Set[Path] = set()
    output_local_candidates: Set[Path] = set()

    try:
        obj = json.loads(contracts_file.read_text(encoding="utf-8"))
    except Exception as e:
        raise RuntimeError(f"Failed to parse contracts file: {contracts_file} ({e})") from e

    if not isinstance(obj, dict):
        return files, dirs, output_local_candidates

    for addr, info in obj.items():
        if not isinstance(info, dict):
            continue

        source_export_dir = info.get("source_export_dir")
        if isinstance(source_export_dir, str) and source_export_dir:
            addr_dir = _as_repo_path(repo_root, source_export_dir)
            dirs.add(addr_dir)
            parent = addr_dir.parent
            if parent.name.startswith("tx_contracts_") and parent.parent.name == "sources":
                dirs.add(parent)

        source_files = info.get("source_files")
        if isinstance(source_files, list):
            for p in source_files:
                if isinstance(p, str) and p:
                    files.add(_as_repo_path(repo_root, p))

        for key in (
            "source_index_file",
            "abi_file",
            "optimized_sol_file",
            "raw_sol_file",
            "decompiled_abi_file",
        ):
            p = info.get(key)
            if isinstance(p, str) and p:
                files.add(_as_repo_path(repo_root, p))

        if info.get("decompiled") is True and isinstance(addr, str) and addr.startswith("0x") and len(addr) >= 12:
            prefix = addr[2:12]
            output_local_candidates.add(repo_root / "output" / "local" / f"Contract_{prefix}-decompiled.sol")
            output_local_candidates.add(repo_root / "output" / "local" / f"Contract_{prefix}-abi.json")

    return files, dirs, output_local_candidates


def main() -> int:
    ap = argparse.ArgumentParser(description="Cleanup tx artifacts by tx hash")
    ap.add_argument("--tx", required=True, help="transaction hash, e.g. 0xabc...")
    ap.add_argument("--dry-run", action="store_true", help="print actions without deleting")
    ap.add_argument("--repo-root", default=".", help="repo root (default: current directory)")
    ap.add_argument("--log-dir", default="log", help="log directory (default: log)")
    ap.add_argument("--transactions-dir", default="transactions", help="transactions directory (default: transactions)")
    args = ap.parse_args()

    tx = args.tx.strip()
    if not (tx.startswith("0x") and len(tx) >= 10):
        raise SystemExit("Invalid tx format: must start with 0x and be at least 10 characters long")

    repo_root = Path(args.repo_root).resolve()
    log_dir = _as_repo_path(repo_root, args.log_dir)
    tx_dir = _as_repo_path(repo_root, args.transactions_dir) / tx

    tx_short = tx[:10]

    tx_log_dir = (log_dir / tx).resolve()
    output_local_tx_dir = (repo_root / "output" / "local" / tx).resolve()

    referenced_files: Set[Path] = set()
    referenced_dirs: Set[Path] = set()
    output_local_files: Set[Path] = set()

    contracts_files: list[Path] = []
    if tx_log_dir.exists():
        contracts_files.extend(list(_iter_contract_files(tx_log_dir, tx_short)))
    contracts_files.extend(list(_iter_contract_files(log_dir, tx_short)))
    contracts_files = sorted(set(contracts_files))
    for cf in contracts_files:
        f, d, out_local = _extract_paths_from_contracts_file(cf, repo_root=repo_root)
        referenced_files |= f
        referenced_dirs |= d
        output_local_files |= out_local

    log_candidates = set(log_dir.glob(f"*{tx_short}*"))
    to_delete_dirs = {tx_dir} | referenced_dirs
    if tx_log_dir.exists():
        to_delete_dirs.add(tx_log_dir)
    if output_local_tx_dir.exists():
        to_delete_dirs.add(output_local_tx_dir)

    to_delete_files = referenced_files | output_local_files | log_candidates

    deleted_count = 0

    for d in sorted(to_delete_dirs, key=lambda p: len(str(p)), reverse=True):
        if _safe_remove(d, repo_root=repo_root, dry_run=args.dry_run):
            deleted_count += 1

    for f in sorted(to_delete_files, key=lambda p: len(str(p)), reverse=True):
        if not f.exists():
            continue
        if _safe_remove(f, repo_root=repo_root, dry_run=args.dry_run):
            deleted_count += 1

    print(
        f"Done. tx={tx} tx_short={tx_short} contracts_files={len(contracts_files)} deleted_items={deleted_count} dry_run={args.dry_run}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
